### ISSUE TITLE
Add in CI/CD

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/JasonYao.github.io#2]
## TODO
- [x] Setup netlify CMS
- [x] Setup netlify Git Gateway
- [x] Add in admin editor account
- [x] Replace build badge in README with netlify build status

**Comment by JasonYao** [comment]
Decided not to do any of the netlify stuff, and added in the build status badge with https://github.com/JasonYao/JasonYao.github.io/commit/27ba272268866f0250cc2e36008e7652771b5a53.

CD itself ran starting from 3027babae1643f7dd19f34462d121edc3bf3f3c4 and began being consistently correct after the bugfix with 9d9baface42329e668953071fece4b1f6e85710e
