### ISSUE TITLE
Add in linters

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/JasonYao.github.io#3]
## TODO
- [ ] Add in toml linter for config
- [x] Add in yaml front-matter linter for posts
- [x] Add in JSON linter for generated deployment and post metadata

**Comment by JasonYao** [comment]
Add in JSON linter for generated deployment and post metadata

**Comment by JasonYao** [comment]
html and json validation can be copy pasta from https://github.com/JasonYao/deprecated-old-2017-site/blob/source/bin/test

https://pkg.go.dev/github.com/Ainiroad/go-toml/cmd/tomll looks like a good linter that we can pull in for the toml config

**Comment by JasonYao** [comment]
It looks like the toml linter is actually a part of the larger [go-toml](https://github.com/pelletier/go-toml), and we can install via `go install github.com/pelletier/go-toml/cmd/tomll`

**Comment by JasonYao** [comment]
Added in tomll code commented out, since it strips comments. not too big if the toml file doesn't have linting, but everything else works as of https://github.com/JasonYao/JasonYao.github.io/commit/8f6cc0f96cbf81aa95e16c8543f6a2dc0ba53e29
