### ISSUE TITLE
Add in search bar for posts

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/JasonYao.github.io#4]
## TODO
- [x] Add in ability to search posts by tags, categories, keywords, etc.
- [ ] Ideally should have type ahead/search hinting
- [x] Should have no backend dependencies, and do everything all from the FE

## Info
- [Hugo docs](https://gohugo.io/tools/search/)
- [Lunr.js](https://lunrjs.com/)
- [Fuse.js](https://fusejs.io/)
